# Generated by Django 4.2.19 on 2025-03-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagaduriasLinix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_nomina', models.CharField(max_length=200)),
                ('nit', models.CharField(max_length=200)),
                ('n_razon', models.CharField(max_length=200)),
                ('f_creacion', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=200)),
                ('k_tipoem', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('ciudad', models.CharField(max_length=200)),
                ('num_representante', models.CharField(max_length=200)),
                ('representante', models.CharField(max_length=200)),
                ('k_nomina', models.CharField(max_length=200)),
                ('num_asociados', models.CharField(max_length=200)),
                ('num_cdat', models.CharField(max_length=200)),
                ('num_cooviahorros', models.CharField(max_length=200)),
                ('num_creditos', models.CharField(max_length=200)),
                ('num_ahorroVista', models.CharField(max_length=200)),
            ],
        ),
    ]
